# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(error_messages={'unique': 'Invalid Beacon name - This name already exists in the DB.'}, max_length=20, unique=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
