# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0005_auto_20171120_1205'),
        ('Tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconmodel',
            name='WeatherObserver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device2beacon', to='Devices.DeviceModel'),
        ),
    ]
