# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0002_auto_20180404_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'permissions': (('view_heating_subsystem', 'Can view the Heating subsystem'), ('view_garden_subsystem', 'Can view the Garden subsystem'), ('view_access_subsystem', 'Can view the Access subsystem')),
            },
        ),
        migrations.AlterField(
            model_name='ruleitems',
            name='PreVar1',
            field=models.CharField(blank=True, choices=[('', ''), ('not ', 'NOT')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='ruleitems',
            name='PreVar2',
            field=models.CharField(blank=True, choices=[('', ''), ('not ', 'NOT')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='subsystems',
            name='Name',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Heating control'), (1, 'Garden control'), (2, 'Access control')]),
        ),
    ]
