# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0003_auto_20180418_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('view_heating_subsystem', 'Can view the Heating subsystem'), ('view_garden_subsystem', 'Can view the Garden subsystem'), ('view_access_subsystem', 'Can view the Access subsystem'), ('reset_system', 'Can force a reset of the system'), ('check_updates', 'Can check for updates of the system'), ('view_devicesapp', 'Can view the devicesAPP'), ('view_reportingapp', 'Can view the reportingAPP'), ('view_subsystemsapp', 'Can view the subsystemsAPP'), ('view_configurationapp', 'Can access to the configurationAPP')), 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
    ]
