# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0004_auto_20180418_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thermostats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RITM', models.OneToOneField(help_text='The rule item that the thermostat is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='ruleitem2thermostat', to='MainAPP.RuleItems')),
            ],
            options={
                'verbose_name': 'Thermostat',
                'verbose_name_plural': 'Thermostats',
            },
        ),
    ]
