# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0006_auto_20180430_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationvarweeklyschedules',
            options={'permissions': (('view_AutomationVarWeeklySchedules', 'Can see available automation schedules'), ('activate_AutomationVarWeeklySchedules', 'Can change the state of the schedules')), 'verbose_name': 'Automation var weekly schedule', 'verbose_name_plural': 'Automation var weekly schedules'},
        ),
        migrations.AlterModelOptions(
            name='inlinedaily',
            options={'verbose_name': 'Automation var hourly schedule', 'verbose_name_plural': 'Automation var hourly schedules'},
        ),
        migrations.AddField(
            model_name='automationvarweeklyschedules',
            name='Overriden',
            field=models.BooleanField(default=False),
        ),
    ]
