# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0007_auto_20180502_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationvariables',
            name='OverrideTime',
            field=models.PositiveSmallIntegerField(default=3600),
        ),
    ]
