# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0008_automationvariables_overridetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FACILITY_NAME', models.CharField(default='My house', max_length=100)),
                ('WIFI_IP', models.GenericIPAddressField(default='10.10.10.1', protocol='IPv4')),
                ('WIFI_MASK', models.GenericIPAddressField(default='255.255.255.0', protocol='IPv4')),
                ('WIFI_GATE', models.GenericIPAddressField(default='10.10.10.1', protocol='IPv4')),
                ('WIFI_SSID', models.CharField(default='DIY4dot0', max_length=50)),
                ('ETH_IP', models.GenericIPAddressField(default='192.168.0.160', protocol='IPv4')),
                ('ETH_MASK', models.GenericIPAddressField(default='255.255.255.0', protocol='IPv4')),
                ('ETH_GATE', models.GenericIPAddressField(default='192.168.0.1', protocol='IPv4')),
                ('SITE_DNS', models.CharField(default='myDIY4dot0House.net', max_length=100)),
            ],
            options={
                'verbose_name': 'Settings',
            },
        ),
    ]
