# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0009_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='VERSION_AUTO_DETECT',
            field=models.BooleanField(default=True, help_text='Automatically checks the repository for new software', verbose_name='Autodetect new software releases'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='VERSION_AUTO_UPDATE',
            field=models.BooleanField(default=False, help_text='Automatically updates to (and applies) the latest software', verbose_name='Apply automatically new software releases'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ETH_GATE',
            field=models.GenericIPAddressField(default='192.168.0.1', help_text='This is the gateway IP of the LAN network that is providing the internet access.', protocol='IPv4', verbose_name='Gateway of the LAN network'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ETH_IP',
            field=models.GenericIPAddressField(default='192.168.0.160', help_text='This is the IP for the LAN network that is providing the internet access.', protocol='IPv4', verbose_name='IP address for the LAN network'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ETH_MASK',
            field=models.GenericIPAddressField(default='255.255.255.0', help_text='This is the mask for the LAN network that is providing the internet access.', protocol='IPv4', verbose_name='Mask for the LAN network'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='FACILITY_NAME',
            field=models.CharField(default='My house', max_length=100, verbose_name='Name of the installation'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='SITE_DNS',
            field=models.CharField(default='myDIY4dot0House.net', help_text='This is the DNS address that gives access to the application from the internet.', max_length=100, verbose_name='Name of the domain to access the application'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='WIFI_GATE',
            field=models.GenericIPAddressField(default='10.10.10.1', help_text='This is the gateway for the WiFi network generated to communicate with the slaves', protocol='IPv4', verbose_name='WIFI network gateway'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='WIFI_IP',
            field=models.GenericIPAddressField(default='10.10.10.1', help_text='This is the IP address for the WiFi network generated to communicate with the slaves', protocol='IPv4', verbose_name='IP address for the WIFI network'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='WIFI_MASK',
            field=models.GenericIPAddressField(default='255.255.255.0', help_text='This is the mask of the WiFi network generated to communicate with the slaves', protocol='IPv4', verbose_name='WIFI network mask'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='WIFI_SSID',
            field=models.CharField(default='DIY4dot0', help_text='This is the name of the WiFi network generated to communicate with the slaves', max_length=50, verbose_name='WIFI network identificator'),
        ),
    ]
