# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0010_auto_20180521_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='WIFI_PASSW',
            field=models.CharField(default='DIY4dot0', help_text='This is the encryption password for the WIFI network', max_length=50, verbose_name='WIFI network passphrase'),
        ),
    ]
