# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0011_sitesettings_wifi_passw'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='PROXY_CREDENTIALS',
            field=models.BooleanField(default=True, help_text='Increased access security by including an additional barrier on the proxy.', verbose_name='Require credentials to access the server'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='PROXY_PASSW1',
            field=models.CharField(default='user1', help_text='First username password.', max_length=10, verbose_name='Password for username 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='PROXY_USER1',
            field=models.CharField(default='user1', help_text='First username enabled to get through the proxy barrier.', max_length=10, verbose_name='Username 1'),
        ),
    ]
