# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0012_auto_20180522_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='PROXY_PASSW1',
            field=models.CharField(default='DIY4dot0', help_text='First username password.', max_length=10, verbose_name='Password for username 1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='PROXY_USER1',
            field=models.CharField(default='DIY4dot0', help_text='First username enabled to get through the proxy barrier.', max_length=10, verbose_name='Username 1'),
        ),
    ]
