# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0014_automationrules_edgeexec'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='NTPSERVER_RESTART_TIMEDELTA',
            field=models.PositiveSmallIntegerField(default=5, help_text='Time difference in minutes that will trigger a restart of the NTP server', verbose_name='NTP server restart time delta'),
        ),
    ]
