# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0015_sitesettings_ntpserver_restart_timedelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='PROXY_PASSW2',
            field=models.CharField(default='DIY4dot0', help_text='First username password.', max_length=10, verbose_name='Password for username 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='PROXY_USER2',
            field=models.CharField(default='user2', help_text='First username enabled to get through the proxy barrier.', max_length=10, verbose_name='Username 2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='PROXY_USER1',
            field=models.CharField(default='user1', help_text='First username enabled to get through the proxy barrier.', max_length=10, verbose_name='Username 1'),
        ),
    ]
