# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0018_auto_20180529_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='VERSION_CODE',
            field=models.CharField(default='', max_length=100, verbose_name='Code of the version of the application framework'),
        ),
    ]
