# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0019_sitesettings_version_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='FACILITY_NAME',
            field=models.CharField(default='My house', help_text='Descriptive name for the installation.', max_length=100, verbose_name='Name of the installation'),
        ),
    ]
