# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0020_auto_20180619_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystems',
            name='Name',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Heating control'), (1, 'Garden control'), (2, 'Access control'), (3, 'Electric system')]),
        ),
    ]
