# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0021_auto_20180829_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcalculations',
            name='Periodicity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'With every new value'), (1, 'Every hour'), (2, 'Every day at 0h'), (5, 'Every day at 12h'), (3, 'Every week'), (4, 'Every month')], help_text='How often the calculation will be updated'),
        ),
    ]
