# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-24 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0022_auto_20180924_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalcalculations',
            options={'verbose_name': 'Additional calculation', 'verbose_name_plural': 'Additional calculations'},
        ),
    ]
