# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0023_auto_20180924_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='VERSION_DEVELOPER',
            field=models.BooleanField(default=False, help_text='Tracks the development versions (may result in unstable behaviour)', verbose_name='Update with the new software development versions'),
        ),
    ]
