# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0024_sitesettings_version_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcalculations',
            name='Periodicity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'With every new value'), (1, 'Every hour'), (2, 'Every day at 0h'), (3, 'Every week'), (4, 'Every month')], help_text='How often the calculation will be updated'),
        ),
    ]
