# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0026_additionalcalculations_timespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationvariables',
            name='Tendency',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
