# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0027_automationvariables_tendency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationvariables',
            name='Tendency',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
