# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-27 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0033_sitesettings_telegram_chatid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('view_heating_subsystem', 'Can view the Heating subsystem'), ('view_garden_subsystem', 'Can view the Garden subsystem'), ('view_access_subsystem', 'Can view the Access subsystem'), ('reset_system', 'Can force a reset of the system'), ('check_updates', 'Can check for updates of the system'), ('view_devicesapp', 'Can view the devicesAPP'), ('view_reportingapp', 'Can view the reportingAPP'), ('view_subsystemsapp', 'Can view the subsystemsAPP'), ('view_configurationapp', 'Can access to the configurationAPP'), ('change_automationvar', 'Can change the value of an automation variable')), 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='VERSION_DEVELOPER',
            field=models.BooleanField(default=False, help_text='Tracks the development versions (may result in unstable behaviour)', verbose_name='Follow the beta development versions'),
        ),
    ]
