# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-02 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0034_auto_20181227_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationvariables',
            name='Tendency',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
