# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-04 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0035_auto_20190102_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermostats',
            name='Inverted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thermostats',
            name='StatusVar',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='MainAPP.AutomationVariables'),
            preserve_default=False,
        ),
    ]
