# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0036_auto_20190204_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='VERSION_CODE',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Code of the version of the application framework'),
        ),
    ]
