# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-28 21:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0037_auto_20190226_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationvariables',
            name='numSamples',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
