# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0039_auto_20190314_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationvariables',
            name='CalculateDuty',
            field=models.BooleanField(default=False),
        ),
    ]
