# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0040_automationvariables_calculateduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcalculations',
            name='Delay',
            field=models.PositiveSmallIntegerField(default=0, help_text='What is the delay (in hours) for the calculation from 00:00 h'),
        ),
    ]
