# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-16 10:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0041_additionalcalculations_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcalculations',
            name='Delay',
            field=models.PositiveSmallIntegerField(default=0, help_text='What is the delay (in hours) for the calculation from 00:00 h', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
