# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0043_additionalcalculations_miscelaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcalculations',
            name='Calculation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Duty cycle OFF'), (1, 'Duty cycle ON'), (2, 'Mean value'), (3, 'Max value'), (4, 'Min value'), (5, 'Cummulative sum'), (6, 'Integral over time'), (7, 'Operation with two variables')]),
        ),
        migrations.AlterField(
            model_name='automationvariables',
            name='Label',
            field=models.CharField(max_length=150),
        ),
    ]
