# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0044_auto_20190416_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcalculations',
            name='SourceVar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sourcevar', to='MainAPP.AutomationVariables'),
        ),
    ]
