# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0045_auto_20190416_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcalculations',
            name='Scale',
            field=models.FloatField(default=1, help_text='Constant to multiply the result of the calculation'),
        ),
    ]
