# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0002_auto_20180404_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindevicevarweeklyschedules',
            options={'permissions': (('view_maindevicevarweeklyschedules', 'Can see available automation schedules'), ('activate_maindevicevarweeklyschedules', 'Can change the state of the schedules')), 'verbose_name': 'Main device var weekly schedule', 'verbose_name_plural': 'Main device var weekly schedules'},
        ),
    ]
