# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0003_auto_20180418_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inlinedaily',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='inlinedaily',
            name='Weekly',
        ),
        migrations.AlterUniqueTogether(
            name='maindevicevarweeklyschedules',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='maindevicevarweeklyschedules',
            name='Days',
        ),
        migrations.RemoveField(
            model_name='maindevicevarweeklyschedules',
            name='Var',
        ),
        migrations.DeleteModel(
            name='inlineDaily',
        ),
        migrations.DeleteModel(
            name='MainDeviceVarWeeklySchedules',
        ),
    ]
