# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0006_auto_20180829_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastergpios',
            name='NotificationFalse',
            field=models.BooleanField(default=False, help_text='Send notification when the rule evaluates to False'),
        ),
        migrations.AddField(
            model_name='mastergpios',
            name='NotificationTrue',
            field=models.BooleanField(default=False, help_text='Send notification when the rule evaluates to True'),
        ),
    ]
