# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0009_auto_20180918_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagrams',
            name='Enable',
            field=models.BooleanField(default=True, help_text='Enables the datagram to be queried'),
        ),
    ]
