# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0010_datagrams_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.RemoveField(
            model_name='devicecommands',
            name='HumanTag',
        ),
        migrations.AlterField(
            model_name='devicecommands',
            name='Identifier',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='parametervalues',
            name='Command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevicesAPP.DeviceCommands'),
        ),
        migrations.AddField(
            model_name='parametervalues',
            name='Parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DevicesAPP.CommandParameters'),
        ),
        migrations.AddField(
            model_name='devicecommands',
            name='Parameters',
            field=models.ManyToManyField(through='DevicesAPP.ParameterValues', to='DevicesAPP.CommandParameters'),
        ),
    ]
