# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-27 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0011_auto_20190127_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommands',
            name='Label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
