# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-29 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0013_auto_20190127_2152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicecommands',
            unique_together=set([]),
        ),
    ]
