# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-16 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0014_auto_20190129_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindevicevars',
            name='Label',
            field=models.CharField(help_text='Unique identifier for the variable.', max_length=150, unique=True),
        ),
    ]
