# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-13 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0015_auto_20190416_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='Code',
            field=models.PositiveSmallIntegerField(blank=True, error_messages={'unique': 'Invalid device code - This code already exists in the DB.'}, help_text='Unique byte-type identifier of the device. It is used to identify the device within the communication frames.', null=True),
        ),
        migrations.AlterField(
            model_name='devicetypes',
            name='Connection',
            field=models.PositiveSmallIntegerField(choices=[(0, 'LOCAL'), (1, 'REMOTE OVER TCP'), (3, 'REMOTE OVER RS485'), (2, 'MEMORY')], help_text='The connection can be: \n                                                                    - LOCAL for devices that connect to a pin of the Master unit.\n                                                                    - REMOTE OVER TCP for devices communicating through the WiFi interface.\n                                                                    - REMOTE OVER RS485 for devices communicating through the RS485 interface.\n                                                                    - MEMORY for devices that reside in the memory of the Master unit.\n                                                                    '),
        ),
    ]
