# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0016_auto_20190613_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='Baudrate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(110, '110'), (300, '300'), (600, '600'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (38400, '38400'), (57600, '57600'), (115200, '115200'), (128000, '128000'), (256000, '256000')], help_text='Baudrate for the communication.', null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='Parity',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('O', 'Odd'), ('E', 'Even')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='Port',
            field=models.CharField(blank=True, choices=[('COM1', 'COM1'), ('COM3', 'COM3')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='Stopbits',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2')], help_text='Number of stopbits on the frame.', null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='Code',
            field=models.PositiveSmallIntegerField(blank=True, error_messages={'unique': 'Invalid device code - This code already exists in the DB.'}, help_text='Identifier of the device. It is used to identify the device within the communication frames.', null=True),
        ),
    ]
