# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-15 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesAPP', '0017_auto_20190723_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='Port',
            field=models.CharField(blank=True, choices=[('/dev/ttyAMA0', '/dev/ttyAMA0')], max_length=100, null=True),
        ),
    ]
