# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCalculationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodicity', models.PositiveSmallIntegerField(choices=[(0, 'With every new value'), (1, 'Every hour'), (2, 'Every day'), (3, 'Every week'), (4, 'Every month')], help_text='How often the calculation will be updated')),
                ('Calculation', models.PositiveSmallIntegerField(choices=[(0, 'Duty cycle OFF'), (1, 'Duty cycle ON'), (2, 'Mean value'), (3, 'Max value'), (4, 'Min value'), (5, 'Cummulative sum'), (6, 'Integral over time')])),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=50, unique=True)),
                ('Active', models.BooleanField(default=False)),
                ('OnError', models.PositiveSmallIntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('OperatorPrev', models.CharField(blank=True, choices=[('&', 'AND'), ('|', 'OR')], max_length=2, null=True)),
                ('Action', models.CharField(blank=True, max_length=500)),
                ('PreviousRule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_rule', to='HomeAutomation.AutomationRuleModel')),
            ],
            options={
                'verbose_name': 'Automation rule',
                'verbose_name_plural': 'Automation rules',
                'permissions': (('view_rules', 'Can see available automation rules'), ('activate_rules', 'Can change the state of the rules'), ('edit_rules', 'Can create and edit a rule')),
            },
        ),
        migrations.CreateModel(
            name='AutomationVariablesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=50)),
                ('Tag', models.CharField(max_length=50)),
                ('Device', models.CharField(max_length=50)),
                ('Table', models.CharField(max_length=50)),
                ('BitPos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Sample', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Automation variable',
                'verbose_name_plural': 'Automation variables',
            },
        ),
        migrations.CreateModel(
            name='inlineDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('Hour0', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour1', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour2', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour3', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour4', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour5', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour6', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour7', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour8', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour9', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour10', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour11', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour12', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour13', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour14', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour15', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour16', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour17', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour18', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour19', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour20', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour21', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour22', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('Hour23', models.PositiveSmallIntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
            ],
            options={
                'verbose_name': 'Main device var hourly schedule',
                'verbose_name_plural': 'Main device var hourly schedules',
            },
        ),
        migrations.CreateModel(
            name='MainDeviceVarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=50, unique=True)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Datatype', models.PositiveSmallIntegerField(choices=[(0, 'Float'), (1, 'Integer')], default=0)),
                ('PlotType', models.CharField(choices=[('line', 'Hard Line'), ('spline', 'Smoothed Line'), ('column', 'Bars'), ('area', 'Area')], default='line', max_length=10)),
                ('Units', models.CharField(max_length=10)),
                ('UserEditable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Main device var',
                'verbose_name_plural': 'Main device vars',
            },
        ),
        migrations.CreateModel(
            name='MainDeviceVarWeeklyScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=50, unique=True)),
                ('Active', models.BooleanField(default=False)),
                ('LValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('HValue', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Days', models.ManyToManyField(blank=True, to='HomeAutomation.inlineDaily')),
                ('Var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeAutomation.MainDeviceVarModel')),
            ],
            options={
                'verbose_name': 'Main device var weekly schedule',
                'verbose_name_plural': 'Main device var weekly schedules',
                'permissions': (('view_schedules', 'Can see available automation schedules'), ('activate_schedule', 'Can change the state of the schedules'), ('edit_schedule', 'Can create and edit a schedule')),
            },
        ),
        migrations.CreateModel(
            name='RuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Order of execution')),
                ('PreVar1', models.CharField(blank=True, choices=[('', 'None'), ('not ', 'NOT')], default='', max_length=3)),
                ('Operator12', models.CharField(choices=[('==', '=='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('!=', '!='), ('&', 'AND'), ('|', 'OR')], max_length=2)),
                ('PreVar2', models.CharField(blank=True, choices=[('', 'None'), ('not ', 'NOT')], default='', max_length=3)),
                ('Var2Hyst', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('IsConstant', models.BooleanField(default=False)),
                ('Constant', models.FloatField(blank=True, null=True)),
                ('Operator3', models.CharField(blank=True, choices=[('&', 'AND'), ('|', 'OR')], max_length=2, null=True)),
                ('Rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeAutomation.AutomationRuleModel')),
                ('Var1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var1', to='HomeAutomation.AutomationVariablesModel')),
                ('Var2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var2', to='HomeAutomation.AutomationVariablesModel')),
            ],
            options={
                'verbose_name': 'Automation expression',
                'verbose_name_plural': 'Automation expressions',
            },
        ),
        migrations.AddField(
            model_name='inlinedaily',
            name='Weekly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeAutomation.MainDeviceVarWeeklyScheduleModel'),
        ),
        migrations.AlterUniqueTogether(
            name='automationvariablesmodel',
            unique_together=set([('Tag', 'BitPos', 'Table')]),
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='RuleItems',
            field=models.ManyToManyField(to='HomeAutomation.RuleItem'),
        ),
        migrations.AddField(
            model_name='additionalcalculationsmodel',
            name='AutomationVar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avar', to='HomeAutomation.AutomationVariablesModel'),
        ),
        migrations.AddField(
            model_name='additionalcalculationsmodel',
            name='MainVar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mvar', to='HomeAutomation.MainDeviceVarModel'),
        ),
        migrations.AlterUniqueTogether(
            name='maindevicevarweeklyschedulemodel',
            unique_together=set([('Label', 'Var')]),
        ),
        migrations.AlterUniqueTogether(
            name='inlinedaily',
            unique_together=set([('Day', 'Weekly')]),
        ),
    ]
