# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationvariablesmodel',
            name='Label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='automationvariablesmodel',
            unique_together=set([('Tag', 'BitPos')]),
        ),
    ]
