# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomeAutomation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRuleModel',
            fields=[
                ('Identifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Expression', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Automation rule',
                'verbose_name_plural': 'Automation rules',
            },
        ),
        migrations.CreateModel(
            name='MainDeviceVarModel',
            fields=[
                ('Label', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Main device var',
                'verbose_name_plural': 'Main device vars',
            },
        ),
    ]
