# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0002_automationrulemodel_maindevicevarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindevicevarmodel',
            name='Units',
            field=models.CharField(default='ºC', max_length=10),
            preserve_default=False,
        ),
    ]
