# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0002_auto_20171119_2001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationvariablesmodel',
            unique_together=set([('Tag', 'BitPos', 'Table')]),
        ),
    ]
