# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0003_maindevicevarmodel_units'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomationRuleModel',
        ),
    ]
