# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0003_auto_20171119_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindevicevarmodel',
            name='PlotType',
            field=models.CharField(choices=[('spline', 'Line'), ('column', 'Bars')], default='spline', max_length=10),
        ),
    ]
