# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0005_auto_20171103_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindevicevarmodel',
            name='Datatype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Float'), (1, 'Integer')], default=0),
        ),
    ]
