# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0005_auto_20171122_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrulemodel',
            name='Action',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
