# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0006_auto_20171124_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrulemodel',
            name='Var2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var2', to='HomeAutomation.AutomationVariablesModel'),
        ),
    ]
