# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0006_maindevicevarmodel_datatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationVariablesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=50)),
                ('Tag', models.CharField(max_length=50)),
                ('Device', models.CharField(max_length=50)),
                ('Table', models.CharField(max_length=50)),
                ('BitPos', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Automation variable',
                'verbose_name_plural': 'Automation variables',
            },
        ),
        migrations.AlterUniqueTogether(
            name='automationvariablesmodel',
            unique_together=set([('Device', 'Table', 'Tag', 'BitPos')]),
        ),
    ]
