# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0007_auto_20171107_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationrulemodel',
            name='Expression',
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='Operator1',
            field=models.CharField(blank=True, choices=[('==', '=='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('!=', '!=')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='Operator12',
            field=models.CharField(blank=True, choices=[('==', '=='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('!=', '!=')], max_length=2),
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='PreviousRule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeAutomation.AutomationRuleModel'),
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='Var1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var1', to='HomeAutomation.AutomationVariablesModel'),
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='Var2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var2', to='HomeAutomation.AutomationVariablesModel'),
        ),
    ]
