# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0007_auto_20171124_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Order of execution')),
                ('PreVar1', models.CharField(blank=True, choices=[('', 'None'), ('not ', 'NOT')], default='', max_length=3)),
                ('Operator12', models.CharField(choices=[('==', '=='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('!=', '!='), ('&', 'AND'), ('|', 'OR')], max_length=2)),
                ('PreVar2', models.CharField(blank=True, choices=[('', 'None'), ('not ', 'NOT')], default='', max_length=3)),
                ('Var2Hyst', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('IsConstant', models.BooleanField(default=False)),
                ('Constant', models.FloatField(blank=True, null=True)),
                ('Operator3', models.CharField(blank=True, choices=[('&', 'AND'), ('|', 'OR')], max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Automation expression',
                'verbose_name_plural': 'Automation expressions',
            },
        ),
        migrations.RemoveField(
            model_name='automationrulemodel',
            name='Operator1',
        ),
        migrations.RemoveField(
            model_name='automationrulemodel',
            name='Operator12',
        ),
        migrations.RemoveField(
            model_name='automationrulemodel',
            name='PreviousRule',
        ),
        migrations.RemoveField(
            model_name='automationrulemodel',
            name='Var1',
        ),
        migrations.RemoveField(
            model_name='automationrulemodel',
            name='Var2',
        ),
        migrations.RemoveField(
            model_name='automationrulemodel',
            name='Var2Hyst',
        ),
        migrations.AlterField(
            model_name='automationrulemodel',
            name='Action',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='Rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeAutomation.AutomationRuleModel'),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='Var1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var1', to='HomeAutomation.AutomationVariablesModel'),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='Var2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='var2', to='HomeAutomation.AutomationVariablesModel'),
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='RuleItems',
            field=models.ManyToManyField(to='HomeAutomation.RuleItem'),
        ),
        migrations.AlterUniqueTogether(
            name='ruleitem',
            unique_together=set([('Rule', 'order')]),
        ),
    ]
