# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0008_auto_20171128_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrulemodel',
            name='OperatorPrev',
            field=models.CharField(blank=True, choices=[('&', 'AND'), ('|', 'OR')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='PreviousRule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_rule', to='HomeAutomation.AutomationRuleModel'),
        ),
    ]
