# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0009_auto_20171129_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindevicevarmodel',
            name='PlotType',
            field=models.CharField(choices=[('line', 'Hard Line'), ('spline', 'Smoothed Line'), ('column', 'Bars'), ('area', 'Area')], default='line', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='ruleitem',
            unique_together=set([]),
        ),
    ]
