# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0009_automationrulemodel_var2hyst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationrulemodel',
            name='FrequencyCheck',
        ),
        migrations.AddField(
            model_name='automationrulemodel',
            name='Action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='automationvariablesmodel',
            name='Sample',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automationrulemodel',
            name='Operator1',
            field=models.CharField(blank=True, choices=[('&', 'AND'), ('|', 'OR')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='automationrulemodel',
            name='Operator12',
            field=models.CharField(choices=[('==', '=='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('!=', '!='), ('&', 'AND'), ('|', 'OR')], max_length=2),
        ),
        migrations.AlterField(
            model_name='automationrulemodel',
            name='Var1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var1', to='HomeAutomation.AutomationVariablesModel'),
        ),
        migrations.AlterField(
            model_name='automationrulemodel',
            name='Var2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var2', to='HomeAutomation.AutomationVariablesModel'),
        ),
        migrations.AlterField(
            model_name='automationvariablesmodel',
            name='BitPos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
