# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0010_auto_20171130_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrulemodel',
            name='OnError',
            field=models.PositiveSmallIntegerField(choices=[(0, 'False'), (1, 'True')], default=0),
        ),
    ]
