# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0011_automationrulemodel_onerror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrulemodel',
            options={'permissions': (('view_rules', 'Can see available automation rules'), ('activate_rules', 'Can change the state of the rules'), ('edit_rules', 'Can create and edit a rule')), 'verbose_name': 'Automation rule', 'verbose_name_plural': 'Automation rules'},
        ),
        migrations.AlterModelOptions(
            name='maindevicevarweeklyschedulemodel',
            options={'permissions': (('view_schedules', 'Can see available automation schedules'), ('activate_schedule', 'Can change the state of the schedules'), ('edit_schedule', 'Can create and edit a schedule')), 'verbose_name': 'Main device var weekly schedule', 'verbose_name_plural': 'Main device var weekly schedules'},
        ),
    ]
