# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0012_auto_20171207_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindevicevarmodel',
            name='UserEditable',
            field=models.BooleanField(default=True),
        ),
    ]
