# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0013_maindevicevarmodel_usereditable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCalculationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodicity', models.PositiveSmallIntegerField(choices=[(1, 'Every hour'), (2, 'Every day'), (3, 'Every week'), (4, 'Every month')], help_text='How often the calculation will be updated')),
                ('Calculation', models.PositiveSmallIntegerField(choices=[(0, 'Duty cycle OFF'), (1, 'Duty cycle ON'), (2, 'Mean value'), (3, 'Max value'), (4, 'Min value'), (5, 'Cummulative sum')])),
                ('AutomationVar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avar', to='HomeAutomation.AutomationVariablesModel')),
            ],
        ),
        migrations.AlterField(
            model_name='maindevicevarmodel',
            name='Value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='additionalcalculationsmodel',
            name='MainVar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mvar', to='HomeAutomation.MainDeviceVarModel'),
        ),
    ]
