# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAutomation', '0014_auto_20171213_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcalculationsmodel',
            name='Periodicity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'With every new value'), (1, 'Every hour'), (2, 'Every day'), (3, 'Every week'), (4, 'Every month')], help_text='How often the calculation will be updated'),
        ),
    ]
