# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Severity', models.PositiveSmallIntegerField(default=0)),
                ('Text', models.CharField(max_length=150)),
                ('IsRead', models.BooleanField(default=False)),
            ],
        ),
    ]
