# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='DatagramId',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='DeviceName',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='boolean_expression',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='variable_pos',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='IsRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='Severity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='Text',
            field=models.CharField(default='text', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
