# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='Profile picture')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('tracking', models.BooleanField(default=False, verbose_name='Location tracking')),
                ('Latitude', models.FloatField(blank=True, null=True, verbose_name='Last known latitude')),
                ('Longitude', models.FloatField(blank=True, null=True, verbose_name='Last known longitude')),
                ('Accuracy', models.FloatField(blank=True, null=True, verbose_name='Last known position accuracy')),
                ('LastUpdated', models.DateTimeField(blank=True, help_text='Datetime of the last data', null=True)),
            ],
            options={
                'permissions': (('view_tracking', 'Can see the real time ubication of a user'), ('change_trackingstate', 'Can change the state of the tracking of a user')),
                'abstract': False,
            },
        ),
    ]
