# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tracking',
            field=models.BooleanField(default=False, verbose_name='Location tracking'),
        ),
    ]
