# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=False, verbose_name='Activate web-push notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Web-push token'),
        ),
    ]
