# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
    ]
