# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180829_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='general_features',
            field=models.CharField(blank=True, default='{}', max_length=5000, verbose_name='General'),
        ),
    ]
