# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171113_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
