# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171114_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Last known latitude'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Last known longitude'),
        ),
    ]
