# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171114_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='LastUpdated',
            field=models.DateTimeField(blank=True, help_text='Datetime of the last data', null=True),
        ),
    ]
