# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_lastupdated'),
        ('profiles', '0009_profile_accuracy'),
    ]

    operations = [
    ]
