# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocalDevices', '0002_auto_20170831_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='DeviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocalDevices.DeviceTypeModel'),
        ),
    ]
