# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalDevices', '0003_auto_20170831_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='RTsampletime',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
