# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocalDevices', '0004_devicemodel_rtsampletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='DeviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.DeviceTypeModel'),
        ),
        migrations.DeleteModel(
            name='DeviceTypeModel',
        ),
    ]
