# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalDevices', '0007_auto_20171030_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='CustomLabels',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
    ]
