# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOmodel',
            fields=[
                ('pin', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(choices=[('OUT', 'Output'), ('IN', 'Input'), ('SENS', 'Sensor')], max_length=4)),
                ('default', models.IntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('value', models.IntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
            ],
            options={
                'verbose_name': 'Input/Output',
                'verbose_name_plural': 'Inputs/Outputs',
            },
        ),
    ]
