# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOmodel',
            fields=[
                ('pin', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('OUT', 'Output'), ('IN', 'Input'), ('SENS', 'Sensor')], max_length=4)),
                ('default', models.IntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
                ('value', models.IntegerField(choices=[(0, 'LOW'), (1, 'HIGH')], default=0)),
            ],
        ),
    ]
