# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_GPIOs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iomodel',
            options={'verbose_name': 'Input/Output', 'verbose_name_plural': 'Inputs/Outputs'},
        ),
        migrations.AlterField(
            model_name='iomodel',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
