# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypeModel',
            fields=[
                ('DeviceType', models.CharField(help_text='Type of the device', max_length=10, primary_key=True, serialize=False)),
                ('Description', models.CharField(help_text='Description of the device', max_length=50)),
                ('MinSampletime', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReportTitle', models.CharField(error_messages={'unique': 'Invalid report title - This title already exists in the DB.'}, help_text='Title of the report', max_length=50, unique=True)),
                ('ReportContentJSON', models.CharField(help_text='Content of the report in JSON format', max_length=20000)),
            ],
            options={
                'permissions': (('add_report', 'Can configure and add reports'), ('view_report', 'Can view reports configured'), ('view_plots', 'Can see the historic plots from any device')),
            },
        ),
    ]
