# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetypemodel',
            old_name='DeviceType',
            new_name='Code',
        ),
    ]
