# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatagramItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HumanTag', models.CharField(max_length=20, unique=True)),
                ('DataType', models.CharField(choices=[('INTEGER', 'Analog Integer'), ('FLOAT', 'Analog Float'), ('DIGITAL', 'Digital')], max_length=10)),
                ('Units', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Datagram item',
                'verbose_name_plural': 'Datagram items',
            },
        ),
        migrations.AlterField(
            model_name='datagrammodel',
            name='Items',
            field=models.ManyToManyField(through='Devices.ItemOrdering', to='Devices.DatagramItemModel'),
        ),
        migrations.AlterField(
            model_name='itemordering',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Devices.DatagramItemModel'),
        ),
        migrations.DeleteModel(
            name='ItemModel',
        ),
    ]
