# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_auto_20171118_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagrammodel',
            name='DeviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DVT2DG', to='Devices.DeviceTypeModel'),
        ),
    ]
