# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_auto_20170904_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypemodel',
            name='Connection',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('REMOTE', 'REMOTE')], default='LOCAL', help_text='Connection of the device', max_length=15),
            preserve_default=False,
        ),
    ]
