# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0003_devicetypemodel_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBTag', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('HumanTag', models.CharField(max_length=20)),
                ('DataType', models.CharField(choices=[('INTEGER', 'Integer'), ('FLOAT', 'Float')], max_length=10)),
                ('Units', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Analog field',
                'verbose_name_plural': 'Analog fields',
            },
        ),
        migrations.CreateModel(
            name='DatagramModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=20)),
                ('Type', models.CharField(choices=[('Synchronous', 'Synchronous'), ('Asynchronous', 'Asynchronous')], max_length=12)),
                ('AnItems', models.ManyToManyField(blank=True, to='Devices.AnalogItemModel')),
            ],
            options={
                'verbose_name': 'Datagram',
                'verbose_name_plural': 'Datagrams',
            },
        ),
        migrations.CreateModel(
            name='DigitalItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBTag', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('HumanTag', models.CharField(max_length=10)),
                ('Bit0', models.CharField(max_length=50)),
                ('Bit1', models.CharField(max_length=50)),
                ('Bit2', models.CharField(max_length=50)),
                ('Bit3', models.CharField(max_length=50)),
                ('Bit4', models.CharField(max_length=50)),
                ('Bit5', models.CharField(max_length=50)),
                ('Bit6', models.CharField(max_length=50)),
                ('Bit7', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Digital field',
                'verbose_name_plural': 'Digital fields',
            },
        ),
        migrations.AlterModelOptions(
            name='devicetypemodel',
            options={'verbose_name': 'Device type', 'verbose_name_plural': 'Device types'},
        ),
        migrations.AlterModelOptions(
            name='reportmodel',
            options={'permissions': (('add_report', 'Can configure and add reports'), ('view_report', 'Can view reports configured'), ('view_plots', 'Can see the historic plots from any device')), 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='datagrammodel',
            name='DeviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.DeviceTypeModel'),
        ),
        migrations.AddField(
            model_name='datagrammodel',
            name='DgItems',
            field=models.ManyToManyField(blank=True, to='Devices.DigitalItemModel'),
        ),
    ]
