# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0004_auto_20170912_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalitemmodel',
            name='DBTag',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='digitalitemmodel',
            name='HumanTag',
            field=models.CharField(max_length=20),
        ),
    ]
