# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0004_auto_20171119_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='DeviceState',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STOPPED'), (1, 'RUNNING')], default=0),
        ),
    ]
