# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0005_auto_20170912_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogitemmodel',
            name='DBTag',
            field=models.CharField(blank=True, editable=False, max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='analogitemmodel',
            name='HumanTag',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='digitalitemmodel',
            name='DBTag',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='digitalitemmodel',
            name='HumanTag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
