# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0005_auto_20171120_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagramitemmodel',
            name='PlotType',
            field=models.CharField(choices=[('spline', 'Line'), ('column', 'Bars')], default='spline', max_length=10),
        ),
    ]
