# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0006_datagramitemmodel_plottype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagramitemmodel',
            name='PlotType',
            field=models.CharField(choices=[('line', 'Hard Line'), ('spline', 'Smoothed Line'), ('column', 'Bars')], default='spline', max_length=10),
        ),
    ]
