# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 19:57
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields

from sortedm2m.operations import AlterSortedManyToManyField

class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0007_auto_20170912_2129'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='datagrammodel',
            name='AnItems',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='Devices.AnalogItemModel'),
        ),
        AlterSortedManyToManyField(
            model_name='datagrammodel',
            name='DgItems',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='Devices.DigitalItemModel'),
        ),
    ]
