# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0007_auto_20171122_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datagramitemmodel',
            name='PlotType',
            field=models.CharField(choices=[('line', 'Hard Line'), ('spline', 'Smoothed Line'), ('column', 'Bars'), ('area', 'Area')], default='spline', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicetypemodel',
            name='Description',
            field=models.CharField(max_length=100),
        ),
    ]
