# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0008_auto_20170912_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypemodel',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='DeviceType_pics/%Y-%m-%d/', verbose_name='DeviceType picture'),
        ),
    ]
