# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0008_auto_20171207_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='NextUpdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
