# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 15:01
from __future__ import unicode_literals

import Devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0009_devicetypemodel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetypemodel',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=Devices.models.path_file_name, verbose_name='DeviceType picture'),
        ),
    ]
