# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from sortedm2m.operations import AlterSortedManyToManyField
class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0010_auto_20170918_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('AnItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Devices.AnalogItemModel')),
                ('DgItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Devices.DigitalItemModel')),
            ],
        ),
        AlterSortedManyToManyField(
            model_name='datagrammodel',
            name='AnItems',
            field=models.ManyToManyField(blank=True, through='Devices.ItemOrdering', to='Devices.AnalogItemModel'),
        ),
        AlterSortedManyToManyField(
            model_name='datagrammodel',
            name='DgItems',
            field=models.ManyToManyField(blank=True, through='Devices.ItemOrdering', to='Devices.DigitalItemModel'),
        ),
        migrations.AddField(
            model_name='itemordering',
            name='datagram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.DatagramModel'),
        ),
        migrations.AlterUniqueTogether(
            name='itemordering',
            unique_together=set([('order', 'datagram')]),
        ),
    ]
