# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0011_auto_20170925_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemordering',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
