# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0012_auto_20170925_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemordering',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Position in the dataframe'),
        ),
    ]
