# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0013_auto_20170925_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=10)),
                ('HumanTag', models.CharField(max_length=50)),
                ('DeviceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.DeviceTypeModel')),
            ],
            options={
                'verbose_name_plural': 'Commands',
                'verbose_name': 'Command',
            },
        ),
        migrations.AlterModelOptions(
            name='itemordering',
            options={'ordering': ('order',), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='Periodicity',
            field=models.CharField(choices=[('DAILY', 'Every day'), ('WEEKLY', 'Every week'), ('MONTHLY', 'Every month')], default='WEEKLY', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemordering',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Position in the dataframe 1-based'),
        ),
        migrations.AlterUniqueTogether(
            name='commandmodel',
            unique_together=set([('DeviceType', 'Identifier')]),
        ),
    ]
