# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0014_auto_20170928_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='Periodicity',
            field=models.CharField(choices=[('DAILY', 'Every day'), ('WEEKLY', 'Every week'), ('MONTHLY', 'Every month')], help_text='Setup the periodicity', max_length=10),
        ),
    ]
