# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0015_auto_20170928_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagrammodel',
            name='Code',
            field=models.PositiveSmallIntegerField(default=0, help_text='Identifier byte-type code'),
            preserve_default=False,
        ),
    ]
