# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0016_datagrammodel_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datagrammodel',
            unique_together=set([('DeviceType', 'Code'), ('DeviceType', 'Identifier')]),
        ),
    ]
