# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0017_auto_20170928_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordering',
            name='Description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
