# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0018_itemordering_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemordering',
            name='Description',
        ),
    ]
