# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 12:44
from __future__ import unicode_literals

import Devices.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0019_remove_itemordering_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('toDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=Devices.models.path_reportfile_name)),
            ],
            options={
                'verbose_name_plural': 'Generated reports',
                'ordering': ('fromDate',),
                'verbose_name': 'Generated report',
            },
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='DataAggregation',
            field=models.CharField(choices=[('NONE', 'No aggregation'), ('HOURLY', 'Every hour'), ('DAILY', 'Every day'), ('MONTHLY', 'Every month')], default='None', help_text='Setup the aggregation of the data', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportitems',
            name='Report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.ReportModel'),
        ),
        migrations.AlterUniqueTogether(
            name='reportitems',
            unique_together=set([('Report', 'fromDate', 'toDate')]),
        ),
    ]
