# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 08:26
from __future__ import unicode_literals

import Devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0021_auto_20171005_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitems',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=Devices.models.path_reportfile_name),
        ),
    ]
