# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0022_auto_20171011_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportitems',
            name='file',
        ),
        migrations.AddField(
            model_name='reportitems',
            name='data',
            field=models.CharField(blank=True, help_text='Data of the report in JSON format', max_length=20000, null=True),
        ),
    ]
