# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0023_auto_20171018_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='DataAggregation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No aggregation'), (1, 'Hourly'), (2, 'Daily'), (4, 'Monthly')], help_text='Data directly from the DB or averaged over a period'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='Periodicity',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Every day'), (3, 'Every week'), (4, 'Every month')], help_text='How often the report will be generated'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='ReportTitle',
            field=models.CharField(error_messages={'unique': 'Invalid report title - This title already exists in the DB.'}, max_length=50, unique=True),
        ),
    ]
