# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0024_auto_20171023_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalitemmodel',
            name='Bit0',
        ),
        migrations.RemoveField(
            model_name='digitalitemmodel',
            name='Bit1',
        ),
        migrations.RemoveField(
            model_name='digitalitemmodel',
            name='Bit2',
        ),
        migrations.RemoveField(
            model_name='digitalitemmodel',
            name='Bit3',
        ),
        migrations.RemoveField(
            model_name='digitalitemmodel',
            name='Bit4',
        ),
        migrations.RemoveField(
            model_name='digitalitemmodel',
            name='Bit5',
        ),
        migrations.RemoveField(
            model_name='digitalitemmodel',
            name='Bit6',
        ),
        migrations.RemoveField(
            model_name='digitalitemmodel',
            name='Bit7',
        ),
    ]
