# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingAPP', '0002_auto_20180418_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='Enable',
            field=models.BooleanField(default=True, help_text='Enables/Disables the generation of the report'),
        ),
    ]
