# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(error_messages={'unique': 'Invalid device name - This name already exists in the DB.'}, max_length=20, unique=True)),
                ('DeviceCode', models.IntegerField(error_messages={'unique': 'Invalid device code - This code already exists in the DB.'}, unique=True)),
                ('DeviceIP', models.GenericIPAddressField(error_messages={'unique': 'Invalid IP - This IP already exists in the DB.'}, protocol='IPv4', unique=True)),
                ('DeviceType', models.CharField(choices=[('GAPQv1', 'GAPQv1'), ('THsensorv1', 'THsensorv1'), ('THsensorv2', 'THsensorv2'), ('DHT11', 'DHT11')], max_length=20)),
                ('DeviceState', models.CharField(choices=[('STOPPED', 'STOPPED'), ('RUNNING', 'RUNNING')], max_length=15)),
                ('Sampletime', models.IntegerField(default=60)),
                ('LastUpdated', models.DateTimeField(blank=True, null=True)),
                ('DeviceHTTPCode', models.IntegerField(blank=True, editable=False, null=True)),
                ('Error', models.CharField(blank=True, editable=False, max_length=100, null=True)),
            ],
            options={
                'permissions': (('view_devices', 'Can see available devices'), ('change_state', 'Can change the state of the devices'), ('add_device', 'Can add new devices to the installation')),
            },
        ),
    ]
