# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteDevices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='DeviceType',
            field=models.CharField(choices=[('GAPQv1', 'GAPQv1'), ('DHT11', 'DHT11'), ('DHT22', 'DHT22')], max_length=20),
        ),
    ]
