# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_auto_20171114_1411'),
        ('RemoteDevices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'permissions': (('view_devices', 'Can see available devices'), ('change_state', 'Can change the state of the devices'), ('add_device', 'Can add new devices to the installation')), 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='DeviceType',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='CustomLabels',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='Type',
            field=models.ForeignKey(default='DHT22', on_delete=django.db.models.deletion.CASCADE, related_name='Remote', to='Devices.DeviceTypeModel'),
            preserve_default=False,
        ),
    ]
