# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteDevices', '0002_auto_20171114_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='DeviceName',
            field=models.CharField(error_messages={'unique': 'Invalid device name - This name already exists in the DB.'}, max_length=50, unique=True),
        ),
    ]
