# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteDevices', '0003_auto_20170904_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'permissions': (('view_devices', 'Can see available devices'), ('change_state', 'Can change the state of the devices'), ('add_device', 'Can add new devices to the installation')), 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='CustomLabels',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
    ]
